### ISSUE TITLE
Allow https assets

### ISSUE THREAD

**Issue by alxy** [RoumenDamianoff/laravel-assets#19]
This plugin generates http asset links by default. It should be possible to load them over https as well. The asset funtion knows a second paramter $secure, so it should also be somehow in any of your method signatures to indicate that.

**Comment by dasuchin** [comment]
Setting the default domain does not fix this. I'm getting it in my controller constructor but it still is using http by default. I can't set secure to always be true due to different environments. It would be nice if it just used what the rest of the application was using instead of forcing one or the other.
